# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# custom: https://www.josef-froehle.de/donate # Replace with a single custom sponsorship URL
github: [Dexus,DeineAgenturUG]
open_collective: dexus
patreon: dexus
#tidelift: npm/pem
custom: https://github.josef-froehle.de/
