name: Build OpenSSL Binaries
on:
  push:
    branches:
    - master
    - devel/v1
    paths:
    - .github/workflows/build_cache.yml
    - bin/**.sh
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TARGET: x86_64-unknown-linux-gnu
jobs:
  build:
    if: github.ref == 'refs/heads/master'
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get install -y haveged ca-certificates
        sudo haveged -w 2048
        mkdir -p openssl
    - name: test me
      shell: bash
      run: | 
        touch openssl/.test
        tar cfJ all_versions.tar.xz openssl/
        ls -lahR openssl/
    - name: Run Prepare
      shell: bash
      run: |
        set +e
        set -x
        echo $PWD
        openssl version
        ./bin/local_build_openssl.sh
    - name: Pack Build
      shell: bash
      run: |
        set +e
        set -x
        echo $PWD
        ls -lahR $PWD
        exec <"./versions"
        while read line; do
          parseLibVersion=(${line//:/ })
          printf "%s\0%s\0" "${parseLibVersion[0]}" "${parseLibVersion[1]}"
        done | xargs -0 -n 2 -P 1 bash -c "./openssl/\${1}_v\${2}/bin/openssl version" --
        tar cfJ all_versions.tar.xz openssl/
    - uses: actions/upload-artifact@v3
      with:
        name: openssl_build
        path: all_versions.tar.xz
